export { TOOL_TREND } from "./trend";
export const TOOL_HLINE = { id: "hline" as const, label: "Horizontal Line", minPoints: 1, maxPoints: 1 };
export const TOOL_VLINE = { id: "vline" as const, label: "Vertical Line", minPoints: 1, maxPoints: 1 };
export const TOOL_RAY = { id: "ray" as const, label: "Ray", minPoints: 2, maxPoints: 2 };
export const TOOL_RECT = { id: "rect" as const, label: "Rectangle", minPoints: 2, maxPoints: 2 };
export const TOOL_CIRCLE = { id: "circle" as const, label: "Circle", minPoints: 2, maxPoints: 2 };
export const TOOL_ARROW = { id: "arrow" as const, label: "Arrow", minPoints: 2, maxPoints: 2 };
export const TOOL_TEXT = { id: "text" as const, label: "Text", minPoints: 1, maxPoints: 1 };
export const TOOL_FIB = { id: "fib" as const, label: "Fibonacci", minPoints: 2, maxPoints: 2 };
export const TOOL_MEASURE = { id: "measure" as const, label: "Measure", minPoints: 2, maxPoints: 2 };
