/**
 * Risk disclaimer constants.
 *
 * Bump DISCLAIMER_VERSION whenever the legal text changes so users must
 * re-accept before accessing the trading terminal. Keep in sync with
 * backend/app/core/disclaimer.py.
 */

export const DISCLAIMER_VERSION = "1.0";

export const DISCLAIMER_TITLE = "⚠️ Risk Disclaimer";

export const DISCLAIMER_TEXT = `Athena is an AI-powered market analysis and trading assistant. All trade ideas, market insights, signals, and recommendations generated by Athena are based on algorithmic analysis, historical data, technical indicators, and artificial intelligence.

Athena DOES NOT guarantee profits, winning trades, or investment success. Financial markets are highly volatile and involve substantial risk. You may lose part or all of your invested capital.

Nothing provided by Athena should be considered financial, investment, or legal advice. All information is provided for informational and educational purposes only.

You are solely responsible for evaluating every trade and making your own trading decisions. Always perform your own analysis and use appropriate risk management before entering any position.

By using Athena, you acknowledge and agree that:

• Athena does not guarantee profitable trades.
• Past performance does not guarantee future results.
• You accept full responsibility for every trade you place.
• The developers, owners, and contributors of Athena are not liable for any financial loss, damages, or consequences resulting from the use of this software.

If you do not agree with these terms, please close the application.`;

export const DISCLAIMER_CHECKBOX_LABEL =
  "I have read and understood this disclaimer and accept full responsibility for my trading decisions.";
