"""add recommendations table

Revision ID: 155df8ac1578
Revises: 59424d68720b
Create Date: 2026-07-14 01:29:11.393376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155df8ac1578'
down_revision: Union[str, Sequence[str], None] = '59424d68720b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('signal', sa.Enum('BUY', 'SELL', 'HOLD', name='recommendation_signal'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('trend', sa.Enum('BULLISH', 'BEARISH', 'SIDEWAYS', name='trend_direction'), nullable=False),
    sa.Column('confluence', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('risk_reward', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendation_symbol', 'recommendations', ['symbol'], unique=False)
    op.create_index('idx_recommendation_symbol_timeframe', 'recommendations', ['symbol', 'timeframe'], unique=False)
    op.create_index('idx_recommendation_timeframe', 'recommendations', ['timeframe'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_symbol'), 'recommendations', ['symbol'], unique=False)
    op.create_index(op.f('ix_recommendations_timeframe'), 'recommendations', ['timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_timeframe'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_symbol'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index('idx_recommendation_timeframe', table_name='recommendations')
    op.drop_index('idx_recommendation_symbol_timeframe', table_name='recommendations')
    op.drop_index('idx_recommendation_symbol', table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
