"""Initial schema

Revision ID: b7fea1fd633f
Revises: 
Create Date: 2026-07-12 23:38:26.913637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fea1fd633f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_candles',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('tick_volume', sa.BigInteger(), nullable=False),
    sa.Column('spread', sa.Integer(), nullable=False),
    sa.Column('real_volume', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'time', name='uq_market_candle')
    )
    op.create_index('idx_market_symbol', 'market_candles', ['symbol'], unique=False)
    op.create_index('idx_market_symbol_time', 'market_candles', ['symbol', 'time'], unique=False)
    op.create_index('idx_market_time', 'market_candles', ['time'], unique=False)
    op.create_index('idx_market_timeframe', 'market_candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_candles_id'), 'market_candles', ['id'], unique=False)
    op.create_index(op.f('ix_market_candles_symbol'), 'market_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_candles_timeframe'), 'market_candles', ['timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_candles_timeframe'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_symbol'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_id'), table_name='market_candles')
    op.drop_index('idx_market_timeframe', table_name='market_candles')
    op.drop_index('idx_market_time', table_name='market_candles')
    op.drop_index('idx_market_symbol_time', table_name='market_candles')
    op.drop_index('idx_market_symbol', table_name='market_candles')
    op.drop_table('market_candles')
    # ### end Alembic commands ###
