"""
Risk disclaimer version constants.

Bump DISCLAIMER_VERSION whenever the legal text changes so users must
re-accept before accessing the trading terminal.

Keep DISCLAIMER_VERSION in sync with frontend/src/constants/disclaimer.ts.
"""

from __future__ import annotations

# Increment this when disclaimer copy changes (e.g. "1.0" -> "1.1").
DISCLAIMER_VERSION = "1.0"

DISCLAIMER_TEXT = (
    "Athena is an AI-powered market analysis and trading assistant. All trade "
    "ideas, market insights, signals, and recommendations generated by Athena "
    "are based on algorithmic analysis, historical data, technical indicators, "
    "and artificial intelligence.\n\n"
    "Athena DOES NOT guarantee profits, winning trades, or investment success. "
    "Financial markets are highly volatile and involve substantial risk. You may "
    "lose part or all of your invested capital.\n\n"
    "Nothing provided by Athena should be considered financial, investment, or "
    "legal advice. All information is provided for informational and educational "
    "purposes only.\n\n"
    "You are solely responsible for evaluating every trade and making your own "
    "trading decisions. Always perform your own analysis and use appropriate "
    "risk management before entering any position.\n\n"
    "By using Athena, you acknowledge and agree that:\n\n"
    "• Athena does not guarantee profitable trades.\n"
    "• Past performance does not guarantee future results.\n"
    "• You accept full responsibility for every trade you place.\n"
    "• The developers, owners, and contributors of Athena are not liable for "
    "any financial loss, damages, or consequences resulting from the use of "
    "this software.\n\n"
    "If you do not agree with these terms, please close the application."
)
